### ISSUE TITLE
Problem with deserializing data structures from System.Collections.Immutable

### ISSUE THREAD

**Issue by Horusiath** [rogeralsing/Wire#13]
At the present moment Wire is not able to correctly deserialize some of the collections from [System.Collections.Immutable](https://www.nuget.org/packages/System.Collections.Immutable) - checked on version 1.1.37 for immutable collection and 0.0.5 for Wire.

Sample to reproduce:

``` csharp
var map = ImmutableDictionary<string, object>.Empty;
var serializer = new Wire.Serializer();

using (var stream = new MemoryStream())
{
    serializer.Serialize(map, stream);
    stream.Position = 0;
    var map2 = serializer.Deserialize(stream);  // exception
}
```

Exception message: **System.MissingMethodException - No parameterless constructor defined for this object**

Stack trace:

>   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    at System.Activator.CreateInstance(Type type)
>    at Wire.Converters.EnumerableSerializerFactory.<>c__DisplayClass3_0.<BuildSerializer>b__1(Stream stream, SerializerSession session)
>    at Wire.ValueSerializers.ObjectSerializer.ReadValue(Stream stream, SerializerSession session)
>    at Wire.Serializer.Deserialize(Stream stream)

**Comment by rogeralsing** [comment]
I'm working on this.

Collections of different types are somewhat tricky.

"Normal" types are just binary serialized, field members are written to the output stream.
However, collections, often hold some sort of backing datastructure with over allocated space, e.g. `List<T>` has a lot of empty pre allocated space in its backing array.
So binary serializng the fields of a collection would result in a very large payload.
(Similar problems exists for hashtables/dictionaries etc)

So, collections should be handled separately, so we can say that if it implements `IDictionary<T>` or `IList<T>` or similar, then it should be serialized in a certain way.
The issue here is that there is no "common" way that collections are implemented, there is no guaranteed constructor that takes an `IEnumerable<T>` to pre fill different collections.
Some collections also have comparison operators attached to them, e.g. dictionaries support different comparison implementations, e.g. casing invariant string comparison for string keys.

What do we consider to be the best default option here, should we add special support for every different collection type?
e.g. we add support for Microsoft.Collections.Immutable?

And should we support serializing extra data like comparison behavior?

**Comment by rogeralsing** [comment]
Done
