### ISSUE TITLE
OSS license for Wire

### ISSUE THREAD

**Issue by Danthar** [rogeralsing/Wire#136]
Hi @rogeralsing ,

It seems you removed the Apache license from the project. Im inquiring because i would like to know what License you plan to change it to. 
The legal department of the company i work for does not allow me to use an OSS project with no license (and some are prohibited outright). So please let me / the community know what your plans are regarding this topic, so I / we can plan accordingly.

Also I can imagine some users who are using Wire with Akka.Net and are using it for persistence would be very interested as well. If they find themselves in the position that they are no longer allowed to use Wire due to License issues, they would possibly have a rather nasty migration path ahead of them.. 

Also, why did you removed it in the first place ?

**Comment by Danthar** [comment]
I noticed you updated the license to GNU v3. 

Im not an expect but if im reading this correctly. It basically means that only other OSS libraries are allowed to use Wire right?

So any proprietary software is out ?

**Comment by Terricide** [comment]
I'm curious about this as well. I was thinking about using it in one of my products but now I can't really anymore. If it was LGPL I could? I'm happy to contribute back fixes.

**Comment by cata** [comment]
Heads-up for whomever can no longer use Wire in commercial closed-source applications due to the move to GPL:

Akka.net's  [Hyperion](https://github.com/akkadotnet/Hyperion) has been forked from Wire prior to the license change and continues to be permissively  licensed under Apache 2.0.

**Comment by Tavriets** [comment]
After investigating actual .Net serializer availabilities, I found that Wire gets absolutely the best score for its performance/serialized size/product integration aspects. Many thanks to @rogeralsing for the great product. I really enjoyed walking though its code and reading a story blog.
... but GPLv3 makes it nearly impossible to use in non-OSS applications. It is a pity indeed, because Wire has a great potential to become a de-facto leader among .Net binary serializers as Newtonsoft.Json is now among JSON ones. But not with this type of license of course...

Just wondering if there is any chance to support dual licensing (e.g. MIT/GPL) as some other OSS libraries do?

**Comment by rogeralsing** [comment]
Apache 2 license re-added.
We are likely adding Wire support in Proto.Actor soon and development will be resumed.
