### ISSUE TITLE
Support for IDictionary

### ISSUE THREAD

**Issue by SIGAN** [rogeralsing/Wire#137]
Without ability to serialize dictionaries it's worthless

**Comment by rogeralsing** [comment]
Wire supports normal .NET Dictionary class, System.Collections.Immutable.Immutabledictionary and F# maps.

Is it a custom dictionary you are trying to serialie?

**Comment by ismaelhamed** [comment]
In my case, the error occurs when declaring properties or fields with an interface instead of the actual concrete implementation, ex.:

```csharp
private readonly IImmutableDictionary<Guid, Work> AcceptedWork = 
    ImmutableDictionary<Guid, Work>.Empty;
```

... then a get

["Wire.ValueSerializers.UnsupportedTypeException: Could not load type 'System.Collections.Immutable.IImmutableDictionary' from assembly 'System.Collections.Immutable'.
   at Wire.ValueSerializers.UnsupportedTypeSerializer.WriteManifest(Stream stream, SerializerSession session)
   at Wire.Serializer.Serialize(Object obj, Stream stream)
   at Akka.Serialization.WireSerializer.ToBinary(Object obj)

**Comment by ismaelhamed** [comment]
Ok, this seems to be related to #127
